export const meta = {
  name: 'tcd-v2-realpath-audit',
  description: 'Audit the TCD v2 engine for real-data-path defects that synthetic smoke cannot reach, plus throughput bottlenecks',
  phases: [
    { title: 'Audit', detail: 'independent lenses, each must RUN code to prove findings' },
    { title: 'Verify', detail: 'adversarially reproduce or refute each finding' },
  ],
}

const REPO = '/home/user/claude-coding'
const FILE = REPO + '/strategies/tcd_v2_00_integrated_all_packs.py'
const BUILD = REPO + '/build'

const FINDINGS = {
  type: 'object',
  properties: {
    lens: { type: 'string' },
    findings: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          symbol: { type: 'string', description: 'function/class where it lives' },
          build_file: { type: 'string', description: 'which build/*.py file to patch' },
          severity: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] },
          problem: { type: 'string' },
          repro: { type: 'string', description: 'the actual script you ran + its output proving it' },
          fix: { type: 'string', description: 'concrete minimal patch' },
        },
        required: ['title', 'severity', 'problem', 'repro', 'fix'],
      },
    },
  },
  required: ['lens', 'findings'],
}

const CONTEXT = [
  'You are auditing a Korean-equity quant backtest engine.',
  '  Assembled single-file build: ' + FILE,
  '  Editable source pieces:     ' + BUILD + '/*.py   (the assembled file is generated from these by tools/build.py)',
  'Patches must be described against the build/*.py pieces, not the assembled file.',
  '',
  '=== WHAT JUST HAPPENED IN PRODUCTION (the user ran it on Windows / Python 3.14 / pandas 2.3+) ===',
  'All strategy files passed 17 contract tests and the synthetic smoke test, then crashed 2 minutes into',
  'the real run at stage L1.UNI with:',
  '    AttributeError: DataFrame object has no attribute name',
  '    (pandas SeriesGroupBy._wrap_agged_manager -> self.obj.name)',
  'Root cause already found and confirmed by reproduction: in build_security_master,',
  '    SEC_MASTER_COLS already contains "delisting_date", and the code does',
  '    reindex(columns=SEC_MASTER_COLS + ["delisting_date"])',
  'which creates a DUPLICATE column, so m["delisting_date"] is a DataFrame not a Series and',
  'groupby(...).agg(delisting_date=("delisting_date","min")) explodes.',
  'A second confirmed bug: _ensure_deps() imports pykrx to probe availability BEFORE',
  'os.environ["KRX_ID"]/["KRX_PW"] are set, and pykrx logs into KRX at import time, so it',
  'builds an unauthenticated session.',
  'DO NOT re-report those two. They are already fixed.',
  '',
  '=== THE STRUCTURAL GAP YOU ARE HERE TO CLOSE ===',
  'The synthetic smoke test (make_synthetic + run_selftest) injects a ready-made panel and therefore',
  'NEVER EXECUTES the real ingest/cleaning functions: build_security_master, fetch_prices,',
  'build_price_panel-from-real-shapes, fetch_dart_financials, tidy_financials, fetch_dart_employees,',
  'fetch_dart_disclosures, hankyung_collect, naver_collect, naver_enrich_detail, download_pdfs,',
  'build_report_master, build_analyst_ledger, fetch_nps_workplaces, resolve_nps_to_corp,',
  'build_nps_panel, fetch_customs_trade, fetch_procurement, fetch_dart_documents,',
  'build_text_similarity, fetch_investor_flows, fetch_pykrx_snapshots, fetch_kind_listing,',
  'fetch_fdr_listing, fetch_fdr_delisting, fetch_dart_corpcode.',
  'That is why a one-line bug survived every test. Your job is to find the REST of that class.',
  '',
  '=== HOW TO WORK ===',
  'The network is BLOCKED in this environment. You cannot call the real endpoints. So you must',
  'build fixture-driven harnesses: import the assembled module with its __main__ orchestrator cut off,',
  'monkeypatch http_get / http_json / http_post / fdr / pykrx_stock / yf to return realistic fixture',
  'payloads, and then ACTUALLY CALL the ingest functions with realistic shapes and volumes.',
  '',
  'Import recipe that works (the module uses @dataclass so it must be registered in sys.modules):',
  '  import types, sys, os',
  '  os.environ["TCD_NO_PIP"]="1"',
  '  src = open(FILE, encoding="utf-8").read()',
  '  src = src[:src.index("def offer_download")]',
  '  src = src.replace("def _pip_install(pkgs: List[str], quiet: bool = True) -> Tuple[bool, str]:",',
  '                    "def _pip_install(pkgs: List[str], quiet: bool = True) -> Tuple[bool, str]:\\n    return True,\'skip\'")',
  '  m = types.ModuleType("tcd"); sys.modules["tcd"] = m',
  '  exec(compile(src, "tcd", "exec"), m.__dict__)',
  '  g = m.__dict__; g["VERBOSE"]=False',
  'Note VAULT is None until a Vault is constructed; construct one against a tmp dir:',
  '  g["VAULT"] = g["Vault"](tmpdir, "TEST")   and also set the module global before calling ingest fns.',
  '',
  'A finding WITHOUT a reproduction script and its real output is worthless — do not report it.',
  'Report ONLY defects you proved. An empty findings list is an acceptable answer.',
  'Do not report style, naming, docstrings, or "consider adding".',
].join('\n')

phase('Audit')

const LENSES = [
  {
    key: 'dupcol-groupby',
    prompt: CONTEXT + [
      '',
      'LENS A: THE DUPLICATE-COLUMN / GROUPBY-AGG DEFECT CLASS (same family as the crash).',
      'Systematically hunt every place a DataFrame can end up with duplicate column labels, and every',
      'groupby/agg/transform that would then break or silently return wrong values.',
      'Concretely:',
      ' - grep every reindex(columns=...), concat, merge (check suffixes and overlapping names),',
      '   assign, pivot_table, join, and every literal column list that is built by list concatenation.',
      '   For each, decide whether duplicates are possible and PROVE it by constructing the input.',
      ' - Check PITStore.asof_join: it merges right columns into a panel that may already contain them.',
      '   What happens when the panel already has revenue_ttm and the table also has revenue_ttm?',
      '   Does the suffix logic actually protect the caller, and do downstream users read the right column?',
      ' - Check pack_c_features: it merges treasury_acq/treasury_canc with suffixes=("","_x") into a P that',
      '   may already contain them (it does, on a second call or after another pack). Prove the behavior.',
      ' - Check build_report_master: named aggregation over a frame built from reindex(columns=sorted(union)).',
      ' - Check every groupby(...)[col] where col could be duplicated.',
      ' - Also: any groupby.agg with a lambda over an empty group, and named aggregation where the output',
      '   name collides with an input name (e.g. name=("name", ...)).',
      'Write one script that programmatically scans the assembled file for these patterns and then a second',
      'script that exercises the suspicious ones with real inputs.',
    ].join('\n'),
  },
  {
    key: 'realpath-crash',
    prompt: CONTEXT + [
      '',
      'LENS B: EXECUTE THE UNEXERCISED REAL INGEST PATH AND MAKE IT CRASH.',
      'Build a fixture harness and actually call, with realistic shapes:',
      '  fetch_fdr_listing, fetch_fdr_delisting, fetch_kind_listing, fetch_dart_corpcode,',
      '  fetch_pykrx_snapshots, build_security_master, fetch_prices, build_price_panel,',
      '  fetch_dart_financials, tidy_financials, fetch_dart_employees, fetch_dart_disclosures,',
      '  hankyung_collect, naver_collect, naver_enrich_detail, download_pdfs, build_report_master,',
      '  build_analyst_ledger, build_consensus_panel, fetch_investor_flows,',
      '  fetch_nps_workplaces, resolve_nps_to_corp, build_nps_panel,',
      '  fetch_customs_trade, fetch_procurement, fetch_dart_documents, build_text_similarity.',
      'For each: feed (a) a realistic success payload, (b) an EMPTY payload, (c) a malformed payload,',
      '(d) a payload missing the columns the code assumes. Record every exception with a traceback.',
      'Realistic fixture shapes matter: FDR listing CSV has columns Code,ISU_CD,Name,Market,Dept,Close,',
      'ChagesRatio,Marcap,Stocks,MarketId (note the ChagesRatio typo); FDR delisting has Symbol,Name,',
      'Market,SecuGroup,Kind,DelistingDate,ToSymbol,ToName,Reason; KIND corpList is an HTML table with',
      'columns 회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역 and 종목코드 comes back',
      'as an INTEGER losing leading zeros; DART fnlttSinglAcntAll returns list of dicts with',
      'rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,thstrm_amount, and',
      'amounts are digit strings possibly with commas, minus, or empty; DART empSttus rows split by',
      'fo_bbm and sexdstn with sm and fyer_salary_totamt as comma strings.',
      'Report each crash with the exact traceback and the minimal patch.',
    ].join('\n'),
  },
  {
    key: 'py314-pandas3',
    prompt: CONTEXT + [
      '',
      'LENS C: PYTHON 3.14 / MODERN PANDAS+NUMPY COMPATIBILITY.',
      'The user runs Python 3.14 on Windows with a recent pandas and numpy. This environment has',
      'Python 3.11 and pandas 2.3.3 / numpy 2.4.6, so you must reason about version drift as well as test.',
      'Hunt for:',
      ' - Removed/deprecated pandas APIs used anywhere: DataFrame.stack(dropna=), groupby.apply on the',
      '   grouping columns, Series.fillna(method=), DataFrame.append, is_categorical_dtype, iteritems,',
      '   inplace patterns, .values.astype("datetime64[M]"), Series.__getitem__ positional, and',
      '   pd.to_datetime without format on ambiguous strings.',
      ' - groupby(...).transform("std", ddof=0) - confirm ddof passthrough works and is not deprecated.',
      ' - observed= default change for categorical groupby, and any groupby on a categorical column that',
      '   omits observed=True (would explode to the full cartesian product of unused categories).',
      '   The panel has cell/cell_l2/cell_l3 as categoricals AND code may become categorical via downcast().',
      '   PROVE whether any groupby on those omits observed=True and measure the blowup.',
      ' - numpy 2.x: np.float_/np.int0 style aliases, copy= semantics of np.array, np.lib.stride_tricks,',
      '   and to_numpy(na_value=) on non-float dtypes.',
      ' - Windows specifics: os.statvfs does not exist on Windows (free_gb), os.replace across drives,',
      '   file locking on Windows for the vault lockfile, path separators baked into any string,',
      '   multiprocessing fork unavailability (already handled? verify the fallback actually works),',
      '   and console encoding for the box-drawing/emoji characters in logs (cp949 UnicodeEncodeError).',
      'That last one is important: the user is on Windows. Prove whether print() of the log banners can',
      'raise UnicodeEncodeError under a cp949 console, and give the fix.',
    ].join('\n'),
  },
  {
    key: 'throughput-blocking',
    prompt: CONTEXT + [
      '',
      'LENS D: THROUGHPUT, BLOCKING, AND THE pykrx LOGIN STORM.',
      'Observed in production: the KRX snapshot stage printed "KRX 로그인 시도" and "KRX 로그인 완료" SIX',
      'times, then later spewed hundreds of "Error occurred in get_market_ticker_and_name: Expecting value:',
      'line 13 column 1 (char 25)" - i.e. KRX returned HTML (a login/error page) instead of JSON.',
      'It took ~128 seconds for 120 months and then still failed.',
      'Investigate and quantify:',
      ' - Read the installed pykrx source (pip show -f pykrx) and determine exactly when it logs in,',
      '   whether the session is global or thread-local, and whether concurrent threads each trigger a',
      '   login that evicts the others (KRX CD011 duplicate-login). Prove it from the source.',
      ' - Given that, what is the correct calling pattern? Single-threaded warmup then N threads? Or',
      '   strictly serial? Or avoid pykrx entirely for this task?',
      ' - fetch_pykrx_snapshots does 120 months x 2 markets. Is there a bulk alternative that gets the same',
      '   information in far fewer calls? Consider: deriving PIT membership from listing_date/delisting_date',
      '   which FDR already gives for 2872 listed + 2526 delisted names, and using snapshots only as a',
      '   cross-check on a coarse grid (e.g. yearly) rather than monthly.',
      ' - fetch_prices issues one request per ticker (~3000). Estimate wall clock and find the bulk path:',
      '   is there a per-date all-ticker endpoint that gets 10 years in ~2500 calls vs 3000, or a',
      '   FDR/Naver bulk route? Quantify which is actually fewer requests and less blocking risk.',
      ' - fetch_dart_financials: 2500 corps x 10 years x 4 reports = 100k calls against a 20k/day limit.',
      '   Is fnlttMultiAcnt (up to 100 corp_codes per call) usable to cut this by 100x for the headline',
      '   accounts, with fnlttSinglAcntAll reserved for what MultiAcnt cannot give? Read the field lists',
      '   and say exactly which of the engine ACCOUNT_PATTERNS items MultiAcnt can and cannot supply.',
      ' - The research collector: quantify requests needed for 10 years at 30k reports/year and whether the',
      '   rate limits make that feasible; propose the concrete parallelism/pagination plan.',
      'Give measured or arithmetic numbers, not adjectives. Where you can time something locally, time it.',
    ].join('\n'),
  },
  {
    key: 'universe-design',
    prompt: CONTEXT + [
      '',
      'LENS E: MULTI-SOURCE PIT UNIVERSE CORRECTNESS.',
      'The universe must be built from FinanceDataReader + pykrx + KIND + Naver + yfinance + DART corpCode,',
      'must include delisted names, and must never contain a name before its listing or after its delisting.',
      'Audit build_security_master and Universe end to end with fixtures:',
      ' - The FDR GitHub cache path: raw.githubusercontent.com/FinanceData/fdr_krx_data_cache/refs/heads/',
      '   master/data/listing/krx/{date}.csv and .../listing/delisting/{date}.csv. Note the delisting file',
      '   in production returned 4172 rows but the code produced 2526 after to_code6 - where did 1646 rows',
      '   go? Reproduce with a realistic delisting fixture and find out. Delisted tickers can have',
      '   non-standard codes; does to_code6 silently drop them? That is survivorship bias.',
      ' - KIND corpList returns 종목코드 as an integer (leading zeros lost). Prove the code handles it.',
      ' - Conflict resolution: when FDR says listing_date X and KIND says Y, which wins and is that logged?',
      ' - Universe.at: verify with fixtures that (a) a name delisted mid-sample IS in the universe before',
      '   and NOT after, (b) a name listed mid-sample is excluded before and included after seasoning,',
      '   (c) the 250-trading-day seasoning uses the right trading calendar when px_daily is sparse.',
      ' - The snapshot path vs the date path: when snapshots exist for a month, the code uses ONLY the',
      '   snapshot and ignores listing/delisting dates. If a snapshot is incomplete (KRX returned partial',
      '   data, which we know happens - see the error spam), the universe silently shrinks for that month.',
      '   Prove this and propose the guard (e.g. reject a snapshot whose size deviates from neighbours).',
      ' - Propose the concrete redesigned build order that uses all five sources with explicit precedence',
      '   and a coverage/conflict audit table.',
    ].join('\n'),
  },
]

const results = await pipeline(
  LENSES,
  l => agent(l.prompt, { label: 'audit:' + l.key, phase: 'Audit', schema: FINDINGS, effort: 'high' }),
  (res, l) => {
    if (!res || !res.findings || res.findings.length === 0) return { lens: l.key, verified: [] }
    return parallel(res.findings.slice(0, 10).map(f => () =>
      agent(CONTEXT + [
        '',
        'You are ADVERSARIALLY VERIFYING a claimed defect. Default to REFUTED unless you reproduce it.',
        '',
        'CLAIM: ' + f.title,
        'SEVERITY: ' + f.severity,
        'WHERE: ' + (f.symbol || '?') + '   build file: ' + (f.build_file || '?'),
        'PROBLEM: ' + f.problem,
        'CLAIMED REPRO: ' + String(f.repro || '').slice(0, 3000),
        'PROPOSED FIX: ' + f.fix,
        '',
        '1. Read the real code. Quote the actual lines.',
        '2. Try to REFUTE: is there a guard elsewhere? is the reviewer misreading pandas semantics?',
        '   is the code path unreachable given how it is actually called from main()/collect_all()?',
        '3. If you cannot refute, RE-RUN the reproduction yourself and paste the real output.',
        '4. Judge the proposed fix; if it is wrong or incomplete, give the correct minimal patch,',
        '   expressed as an exact old-string/new-string edit against the build/*.py file.',
      ].join('\n'),
        { label: 'verify:' + (f.title || '').slice(0, 24), phase: 'Verify', effort: 'high',
          schema: { type: 'object', properties: {
            title: { type: 'string' },
            verdict: { type: 'string', enum: ['CONFIRMED', 'REFUTED', 'PARTIAL'] },
            severity: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] },
            build_file: { type: 'string' },
            symbol: { type: 'string' },
            evidence: { type: 'string' },
            patch_old: { type: 'string', description: 'exact existing text to replace' },
            patch_new: { type: 'string', description: 'exact replacement text' },
            patch_note: { type: 'string' },
          }, required: ['title', 'verdict', 'severity', 'evidence'] } }))
    ).then(vs => ({ lens: l.key, verified: vs.filter(Boolean) }))
  }
)

const all = results.filter(Boolean).flatMap(r => (r.verified || []).map(v => Object.assign({}, v, { lens: r.lens })))
const keep = all.filter(v => v.verdict === 'CONFIRMED' || v.verdict === 'PARTIAL')
log('confirmed ' + keep.length + ' of ' + all.length + ' claims')
return { confirmed: keep, refuted: all.filter(v => v.verdict === 'REFUTED').map(v => v.title) }
